//! Persistent plugin configuration.
//!
//! Settings live in `settings.json` inside the plugin's config directory, which is
//! `$XDG_CONFIG_HOME/nu_plugin_ds` (Linux), `~/Library/Application Support/nu_plugin_ds`
//! (macOS) or `%APPDATA%\nu_plugin_ds` (Windows).

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow};
use serde::{Deserialize, Serialize};

/// Environment variable holding the DeepSeek API key.
pub const ENV_API_KEY: &str = "DEEPSEEK_API_KEY";
/// Environment variable overriding the log/verbose behaviour (accepted values: `1`, `true`).
pub const ENV_BASE_URL: &str = "DEEPSEEK_BASE_URL";
/// Environment variable used to locate the `nu` executable for `cc`.
pub const ENV_NU_BIN: &str = "NU_PLUGIN_DS_NU_BIN";
/// Environment variable overriding the directory settings and sessions live in.
///
/// Useful for keeping a project's conversations next to the project, or for
/// isolating the plugin in tests.
pub const ENV_CONFIG_DIR: &str = "NU_PLUGIN_DS_CONFIG_DIR";

/// The public DeepSeek endpoint.
pub const DEFAULT_BASE_URL: &str = "https://api.deepseek.com";
/// The general purpose, non-thinking model.
pub const DEFAULT_MODEL: &str = "deepseek-chat";
/// The reasoning model, used when thinking is enabled and no other model was picked.
pub const REASONING_MODEL: &str = "deepseek-reasoner";

/// How much reasoning the model should spend on an answer.
///
/// `Off` keeps the request on a plain chat completion. Every other level sends the
/// OpenAI compatible `reasoning_effort` field, which DeepSeek only honours for models
/// that support thinking. If your account rejects the field, set this back to `off`
/// (or pick a non-thinking model).
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum ThinkingEffort {
    #[default]
    Off,
    Low,
    Medium,
    High,
}

impl ThinkingEffort {
    pub const ALL: [ThinkingEffort; 4] = [
        ThinkingEffort::Off,
        ThinkingEffort::Low,
        ThinkingEffort::Medium,
        ThinkingEffort::High,
    ];

    /// The value sent to the API, or `None` when thinking should be disabled.
    pub fn as_api(self) -> Option<&'static str> {
        match self {
            ThinkingEffort::Off => None,
            ThinkingEffort::Low => Some("low"),
            ThinkingEffort::Medium => Some("medium"),
            ThinkingEffort::High => Some("high"),
        }
    }

    /// Short label used in the status bar and pickers.
    pub fn label(self) -> &'static str {
        match self {
            ThinkingEffort::Off => "off",
            ThinkingEffort::Low => "low",
            ThinkingEffort::Medium => "medium",
            ThinkingEffort::High => "high",
        }
    }

    pub fn next(self) -> Self {
        match self {
            ThinkingEffort::Off => ThinkingEffort::Low,
            ThinkingEffort::Low => ThinkingEffort::Medium,
            ThinkingEffort::Medium => ThinkingEffort::High,
            ThinkingEffort::High => ThinkingEffort::Off,
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value.trim().to_ascii_lowercase().as_str() {
            "off" | "none" | "false" | "0" => Some(ThinkingEffort::Off),
            "low" | "minimal" => Some(ThinkingEffort::Low),
            "medium" | "mid" | "default" => Some(ThinkingEffort::Medium),
            "high" | "max" => Some(ThinkingEffort::High),
            _ => None,
        }
    }
}

/// User configurable settings, all optional in the file.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(default, deny_unknown_fields)]
pub struct Settings {
    /// Base URL of the API, without the trailing `/v1`.
    pub base_url: String,
    /// Model used when a session does not pin one.
    pub model: String,
    /// Reasoning level for new sessions.
    pub thinking: ThinkingEffort,
    /// Sampling temperature; ignored by thinking-only models.
    pub temperature: Option<f32>,
    /// Cap on generated tokens per answer.
    pub max_tokens: Option<u32>,
    /// Local token budget for a conversation before it gets compacted.
    ///
    /// `None` means "use whatever window the model has" (see [`model_context_limit`]).
    pub context_limit: Option<u32>,
    /// Fraction of the effective context limit that triggers compaction.
    pub compact_ratio: f32,
    /// How many of the most recent messages are always kept verbatim when compacting.
    pub keep_recent_messages: usize,
    /// System prompt used for new sessions.
    pub system_prompt: Option<String>,
    /// Path to the `nu` executable used to run commands generated by `cc`.
    pub nu_bin: Option<String>,
    /// Whether answers are rendered as markdown in the chat window.
    pub markdown: bool,
    /// Whether chat may offer the file tools to the model.
    pub tools: bool,
    /// Whether reading a file is confirmed too. Off by default: a read cannot change
    /// anything.
    pub confirm_tool_reads: bool,
    /// Whether writing a file is confirmed.
    pub confirm_tool_writes: bool,
    /// Whether running a command is confirmed.
    pub confirm_tool_commands: bool,
    /// How long a `run_nu` command may run before it is killed, in seconds.
    pub tool_command_timeout_secs: u64,
    /// How many tool rounds one turn may use, so a model cannot loop forever.
    pub max_tool_rounds: usize,
}

impl Default for Settings {
    fn default() -> Self {
        Settings {
            base_url: DEFAULT_BASE_URL.to_owned(),
            model: DEFAULT_MODEL.to_owned(),
            thinking: ThinkingEffort::Off,
            temperature: None,
            max_tokens: None,
            context_limit: None,
            compact_ratio: 0.75,
            keep_recent_messages: 8,
            system_prompt: None,
            nu_bin: None,
            markdown: true,
            tools: true,
            confirm_tool_reads: false,
            confirm_tool_writes: true,
            confirm_tool_commands: true,
            tool_command_timeout_secs: 120,
            max_tool_rounds: 8,
        }
    }
}

/// The context window DeepSeek publishes for a model.
///
/// Both of the current models expose 128K tokens, and the API rejects a request that is
/// longer, so this is the number that matters. It is a table rather than a constant so a
/// future model can differ here, and it is used when `context_limit` is not set.
pub fn model_context_limit(model: &str) -> u32 {
    let _ = model;
    128_000
}

impl Settings {
    pub fn load(paths: &ConfigPaths) -> Result<Self> {
        Self::load_from(&paths.settings_file())
    }

    pub fn load_from(path: &Path) -> Result<Self> {
        if !path.exists() {
            return Ok(Settings::default());
        }
        let raw = fs::read_to_string(path)
            .with_context(|| format!("could not read settings from {}", path.display()))?;
        let settings: Settings = serde_json::from_str(&raw)
            .with_context(|| format!("{} is not valid plugin settings", path.display()))?;
        settings.validate()?;
        Ok(settings)
    }

    pub fn save(&self, paths: &ConfigPaths) -> Result<()> {
        let path = paths.settings_file();
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("could not create {}", parent.display()))?;
        }
        let raw = serde_json::to_string_pretty(self)?;
        fs::write(&path, raw).with_context(|| format!("could not write {}", path.display()))
    }

    fn validate(&self) -> Result<()> {
        if !(0.0..=1.0).contains(&self.compact_ratio) {
            return Err(anyhow!(
                "compact_ratio must be between 0 and 1, found {}",
                self.compact_ratio
            ));
        }
        if let Some(limit) = self.context_limit
            && limit < 1_024
        {
            return Err(anyhow!(
                "context_limit must be at least 1024 tokens, found {limit}"
            ));
        }
        if self.max_tool_rounds < 1 {
            return Err(anyhow!(
                "max_tool_rounds must be at least 1, found {}",
                self.max_tool_rounds
            ));
        }
        if self.tool_command_timeout_secs < 1 {
            return Err(anyhow!(
                "tool_command_timeout_secs must be at least 1, found {}",
                self.tool_command_timeout_secs
            ));
        }
        Ok(())
    }

    /// The token budget actually in force: the configured one, or the model's window.
    pub fn effective_context_limit(&self, model: &str) -> u32 {
        self.context_limit
            .unwrap_or_else(|| model_context_limit(model))
    }

    /// The estimated token count that triggers compaction for `model`.
    pub fn compact_at(&self, model: &str) -> usize {
        ((self.effective_context_limit(model) as f32) * self.compact_ratio).max(1.0) as usize
    }

    /// A warning when the configured budget is larger than the model can hold, which means
    /// compaction would only happen after the API has already refused the request.
    pub fn context_limit_warning(&self, model: &str) -> Option<String> {
        let configured = self.context_limit?;
        let window = model_context_limit(model);
        (configured > window).then(|| {
            format!(
                "context_limit is {configured} but `{model}` only holds {window} tokens, so \
                 the API will refuse a request before compaction triggers; the plugin will \
                 compact and retry when that happens"
            )
        })
    }

    /// The base URL normalized to something we can join paths onto.
    pub fn api_base(&self) -> String {
        let trimmed = self.base_url.trim().trim_end_matches('/');
        if trimmed.is_empty() {
            DEFAULT_BASE_URL.to_owned()
        } else {
            trimmed.to_owned()
        }
    }
}

/// Locations of the files the plugin owns.
#[derive(Clone, Debug)]
pub struct ConfigPaths {
    dir: PathBuf,
}

impl ConfigPaths {
    /// Resolve the config directory, creating it if needed.
    ///
    /// `$env.NU_PLUGIN_DS_CONFIG_DIR` wins over the platform default.
    pub fn discover() -> Result<Self> {
        let dir = match std::env::var_os(ENV_CONFIG_DIR).filter(|dir| !dir.is_empty()) {
            Some(dir) => PathBuf::from(dir),
            None => dirs::config_dir()
                .or_else(dirs::home_dir)
                .ok_or_else(|| anyhow!("could not determine a config directory for the plugin"))?
                .join("nu_plugin_ds"),
        };
        fs::create_dir_all(&dir)
            .with_context(|| format!("could not create config directory {}", dir.display()))?;
        Ok(ConfigPaths { dir })
    }

    /// Use a caller supplied directory (used by `--config-dir`).
    pub fn at(dir: impl Into<PathBuf>) -> Self {
        ConfigPaths { dir: dir.into() }
    }

    pub fn dir(&self) -> &Path {
        &self.dir
    }

    pub fn settings_file(&self) -> PathBuf {
        self.dir.join("settings.json")
    }

    pub fn sessions_dir(&self) -> PathBuf {
        self.dir.join("sessions")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn both_models_expose_128k() {
        assert_eq!(model_context_limit("deepseek-chat"), 128_000);
        assert_eq!(model_context_limit("deepseek-reasoner"), 128_000);
        assert_eq!(model_context_limit("some-future-model"), 128_000);
    }

    #[test]
    fn the_configured_limit_wins_over_the_window() {
        let settings = Settings {
            context_limit: Some(4_096),
            ..Settings::default()
        };
        assert_eq!(settings.effective_context_limit("deepseek-chat"), 4_096);
        assert_eq!(settings.compact_at("deepseek-chat"), 3_072);
    }

    #[test]
    fn an_unset_limit_uses_the_model_window() {
        let settings = Settings::default();
        assert_eq!(settings.context_limit, None);
        assert_eq!(
            settings.effective_context_limit("deepseek-chat"),
            model_context_limit("deepseek-chat")
        );
        assert_eq!(settings.compact_at("deepseek-chat"), 96_000);
    }

    #[test]
    fn compact_at_is_never_zero() {
        let settings = Settings {
            context_limit: Some(1_024),
            compact_ratio: 0.0,
            ..Settings::default()
        };
        assert_eq!(settings.compact_at("deepseek-chat"), 1);
    }

    #[test]
    fn warning_only_fires_when_the_budget_exceeds_the_window() {
        let over = Settings {
            context_limit: Some(1_000_000),
            ..Settings::default()
        };
        let warning = over.context_limit_warning("deepseek-chat").unwrap();
        assert!(warning.contains("1000000"), "{warning}");
        assert!(warning.contains("128000"), "{warning}");

        let under = Settings {
            context_limit: Some(65_536),
            ..Settings::default()
        };
        assert_eq!(under.context_limit_warning("deepseek-chat"), None);

        let unset = Settings::default();
        assert_eq!(unset.context_limit_warning("deepseek-chat"), None);
    }

    #[test]
    fn a_small_configured_limit_is_still_rejected() {
        let settings = Settings {
            context_limit: Some(1_023),
            ..Settings::default()
        };
        assert!(settings.validate().is_err());
    }
}
